[shell]
program = "/usr/bin/zsh"

[terminal]
osc52 = "CopyPaste"

[window]
decorations_theme_variant = "dark"

[scrolling]
history = 10000
multiplier = 3

[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]

[font]
normal.family = "JetBrains Mono"
normal.style = "Regular"
bold.family = "JetBrains Mono"
bold.style = "Bold"
italic.family = "JetBrains Mono"
italic.style = "Italic"
size = 12.0

[colors]
draw_bold_text_with_bright_colors = true

# Color scheme taken from here:
# https://github.com/alacritty/alacritty-theme/blob/master/themes/monokai.toml
[colors.primary]
background = "#272822"
foreground = "#f8f8f2"

[colors.normal]
black = "#272822"
red = "#f92672"
green = "#a6e22e"
yellow = "#f4bf75"
blue = "#66d9ef"
magenta = "#ae81ff"
cyan = "#a1efe4"
white = "#f8f8f2"

[colors.bright]
black = "#75715e"
red = "#f92672"
green = "#a6e22e"
yellow = "#f4bf75"
blue = "#66d9ef"
magenta = "#ae81ff"
cyan = "#a1efe4"
white = "#f9f8f5"
